# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=checklist
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 cl_back.wsgi:application
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - SECRET_KEY=ewtc7^l*f3zku6kx*0s(@vea4(1)o+xc+!k=tcm=e@pawcr%ld
      - DEBUG=False
      - ENGINE=django.db.backends.postgresql
      - NAME=checklist
      - USER=admin
      - PASSWORD=Pushkin@144
      - HOST=db
      - PORT=5432
    ports:
      - "8000:8000"  # Add this to expose backend API
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Changed from 3000:80 to 80:80 for production
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
