# Generated by Django 5.1.6 on 2025-03-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_note_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
