# Generated by Django 5.1.6 on 2025-03-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_note_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='scratched_out',
            field=models.BooleanField(default=False),
        ),
    ]
